name: Frontend

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
      - pizza-frontend/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-image:
    name: 'Build frontend image'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pizza-frontend

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: '20.12.2'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - name: NPM install
      run: npm ci
               
    - name: Lint
      run: npm run lint

    - name: Run tests
      run: npm run test-ci
          
    - name: Build application
      run: npm run build   

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ./pizza-frontend
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/pizza-selector-ui:${{ github.sha }}

  deploy-dev:
    runs-on: ubuntu-latest
    environment: DEV
    needs: build-image

    steps:
      - name: 'Login via Azure CLI'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: pizza-selector-ui-dev
          images: '${{ secrets.DOCKERHUB_USERNAME }}/pizza-selector-ui:${{ github.sha }}'

      - name: Check http status code of production site
        uses: lakuapik/gh-actions-http-status@v1
        with:
          sites: '["https://pizza-selector-ui-dev.azurewebsites.net"]'
          expected: '[200]'

  deploy-prod:
    runs-on: ubuntu-latest
    environment: PROD
    needs: deploy-dev

    steps:
      - name: 'Login via Azure CLI'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: pizza-selector-ui-prod
          images: '${{ secrets.DOCKERHUB_USERNAME }}/pizza-selector-ui:${{ github.sha }}'